In [1]:
import pandas as pd
data_a = {'CustomerID': [1, 2, 3, 4, 5],
          'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
          'Region': ['North', 'South', 'North', 'West', 'East']}
df_customers = pd.DataFrame(data_a)
df_customers

   CustomerID     Name Region
0           1    Alice  North
1           2      Bob  South
2           3  Charlie  North
3           4    David   West
4           5      Eve   East

In [3]:
data_b = {'OrderID': ['X100', 'X101', 'X102', 'X103', 'X104', 'X105'],
          'Customer_ID': [1, 3, 3, 6, 2, 2],
          'Amount': [50.0, 75.0, 10.0, 100.0, 25.0, 90.0]}
df_orders = pd.DataFrame(data_b)
df_orders

  OrderID  Customer_ID  Amount
0    X100            1    50.0
1    X101            3    75.0
2    X102            3    10.0
3    X103            6   100.0
4    X104            2    25.0
5    X105            2    90.0

In [ ]:
result_left = pd.merge(df_customers, df_orders, left_on='CustomerID', right_on='Customer_ID', how='left')
result_left

   CustomerID     Name Region OrderID  Customer_ID  Amount
0           1    Alice  North    X100          1.0    50.0
1           2      Bob  South    X104          2.0    25.0
2           2      Bob  South    X105          2.0    90.0
3           3  Charlie  North    X101          3.0    75.0
4           3  Charlie  North    X102          3.0    10.0
5           4    David   West     NaN          NaN     NaN
6           5      Eve   East     NaN          NaN     NaN

A left join in pandas keeps all rows from the left DataFrame and brings in matching rows from the right DataFrame. 

If there is no match, the result will contain NaN (missing values).

All customers are kept (from df_customers — the left table).
Matching orders from df_orders are added.
If a customer has:

- multiple orders → multiple rows appear (e.g., Bob and Charlie)
- no orders → NaN is shown (e.g., David, Eve)